version: "2.4"

services:
  appserver:
    image: node:14-slim
    # user: node
    working_dir: /app
    # environment:
    #   - NODE_ENV=development
    ports:
      - "8080"
    volumes:
      - ./:/app
    command: sh -c "[ ! -d node_modules ] && npm install; npm run docs:dev"
